### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by botbotbotbotboot** [Foo-Manroot/tweet-feed#1] opened 2020-09-02 13:58 UTC
Looks like twitter changed the frontend API.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scraper.py", line 383, in get_tweets
    data = get_user_tweets (username, max_count, older_age)
  File "scraper.py", line 339, in get_user_tweets
    data = process_html (html, max_count, older_age)
  File "scraper.py", line 194, in process_html
    older_tweet = int (parsed.select (".stream-container") [0]["data-min-position"])
IndexError: list index out of range`

**Comment by Foo-Manroot** [comment] 2020-09-02 18:22
Thank you very much for your comment!
I was able to reproduce it and I'm going to look into it.

I'll keep you updated :)

**Comment by Foo-Manroot** [comment] 2020-09-03 17:19
Hi,
I'd like to let you know that I've already discovered how to get all the info, but it needs a lot of work to get it working again.

Apparently, requests are now authenticated; but guests have what seems to be a hardcoded token.
The process to auhtenticate is the following one:

  - Request a bearer token via GET https://abs.twimg.com/responsive-web/client-web/main.a8574df5.js There should be a hardcoded token assigned to the variable 'a'. I think that this token always has the value `AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA`, but I'm not 100% sure

  - With that token added in the headers (`Authorization: Bearer <token>`), request a guest token via POST https://api.twitter.com/1.1/guest/activate.json with no data. This should return a number like 1234566678909876543

The rest of the requests are to be made with those tokens in the headers:
```
Authorization: Bearer <token 1>
x-guest-token: <token 2>
```

  - Get the target user's REST id via GET https://api.twitter.com/graphql/4S2ihIKfF3xhp-ENxvUAfQ/UserByScreenName?variables=%7B%22screen_name%22%3A%22 **<SCREEN_NAME>** %22%2C%22withHighlightedLabel%22%3Atrue%7D

  - Get that user's tweets via GET /2/timeline/profile/ **<USER_REST_ID>** .json?[options...]


I already have everything figured out, but I have to process the information from the REST API to match my library's format

**Comment by botbotbotbotboot** [comment] 2020-09-03 17:39
Amazing work! 

I was using [twitter-scraper](https://github.com/bisguzar/twitter-scraper) for one of my projects. After it broke i did some searching to figure out if i can fix it my own. Then i found your article.

Can i share your findings with that repo users ? Maybe i can try forking also.

**Comment by botbotbotbotboot** [comment] 2020-09-03 17:43
It works!

![It works!](https://media.giphy.com/media/doPrWYzSG1Vao/giphy.gif)

**Comment by Foo-Manroot** [comment] 2020-09-03 17:49
Yeah, sure, you can share it with them no problem.

I'm glad I helped you :)

Also, in case you didn't know that tool (I discovered it by accident a couple of weeks ago), I think that TWINT ( https://github.com/twintproject/twint ) is really active and working properly. Their fix was to use a different endpoint which still returns the static info in mobile.twitter.com

**Closed as completed** 2020-09-03 19:53 UTC

**Comment by botbotbotbotboot** [comment] 2020-09-04 06:41
Thanks.

Yeah i have checked twint but the intended use case is different. Mine is just to get all recent tweets of a user. twint is too heavy.

**Comment by nayaksudeep** [comment] 2020-10-09 11:49
This worked. Awesome!

**Comment by nukopy** [comment] 2020-10-22 03:26
This works for me.

**Comment by synchronizing** [comment] 2020-12-03 21:02
I can confirm that the `Bearer` token is hardcoded for guests.

<img width="1440" alt="Screen Shot 2020-12-03 at 4 02 06 PM" src="https://user-images.githubusercontent.com/2829082/101087933-ee98a800-3580-11eb-819c-91a4de031540.png">

The above is a random request through Safari on an iPhone.
